<a href="https://colab.research.google.com/github/YasuharuSuzuki/23_programing2/blob/main/" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01. 都道府県データをカンマ区切りから空白区切りへ変換する

In [16]:
# drive.mount()を使用してGoogleDriveをMount
# from google.colab import drive
# drive.mount('/content/drive')

# os.chdir()を使用してカレントディレクトリを変更。作成したショーットカット名を使ってパスを指定します。
# import os
# os.chdir('/content/drive/MyDrive/＜作成したショートカット名＞')

# データファイル定義
PREFECTURES_READ_COMMA_PATH = "./data/prefectures_comma.txt"
PREFECTURES_WRITE_PATH = "./data/prefectures.txt"

# ファイルを読み込みながら空白区切りに変換
prefectures2 = []
with open(PREFECTURES_READ_COMMA_PATH, mode="r", encoding="utf_8") as f:
    prefectures_all = f.readlines()
    prefectures_all2 = []
    for prefecture1 in prefectures_all:
        prefectures_all2.append(" ".join(prefecture1.rstrip().split(',')))

In [17]:
# ファイル出力
with open(PREFECTURES_WRITE_PATH, mode="w", encoding="utf_8") as f:
    f.write("\n".join(prefectures_all2))

In [18]:
# ファイルを読み込みながら辞書型で取得
prefectures2 = []
with open(PREFECTURES_WRITE_PATH, mode="r", encoding="utf_8") as f:
    prefectures_all = f.readlines()
    prefectures_dict = {}
    for prefecture1 in prefectures_all:
        prefecture_id, name = prefecture1.split()
        prefectures_dict[prefecture_id] = name

In [19]:
prefectures_dict

{'1': '北海道',
 '2': '青森県',
 '3': '岩手県',
 '4': '宮城県',
 '5': '秋田県',
 '6': '山形県',
 '7': '福島県',
 '8': '茨城県',
 '9': '栃木県',
 '10': '群馬県',
 '11': '埼玉県',
 '12': '千葉県',
 '13': '東京都',
 '14': '神奈川県',
 '15': '新潟県',
 '16': '富山県',
 '17': '石川県',
 '18': '福井県',
 '19': '山梨県',
 '20': '長野県',
 '21': '岐阜県',
 '22': '静岡県',
 '23': '愛知県',
 '24': '三重県',
 '25': '滋賀県',
 '26': '京都府',
 '27': '大阪府',
 '28': '兵庫県',
 '29': '奈良県',
 '30': '和歌山県',
 '31': '鳥取県',
 '32': '島根県',
 '33': '岡山県',
 '34': '広島県',
 '35': '山口県',
 '36': '徳島県',
 '37': '香川県',
 '38': '愛媛県',
 '39': '高知県',
 '40': '福岡県',
 '41': '佐賀県',
 '42': '長崎県',
 '43': '熊本県',
 '44': '大分県',
 '45': '宮崎県',
 '46': '鹿児島県',
 '47': '沖縄県'}

## 02. ワクチンデータを日付ｘ県ごとに集計し、カンマ区切りから空白区切りへ変換する

In [26]:
# データの定義
VACCINATION_READ_COMMA_PATH = "./data/vaccination_comma.txt"
VACCINATION_WRITE_PATH = "./data/vaccination.txt"

# ファイルを読み込みながら空白区切りに変換
vaccination = []
with open(VACCINATION_READ_COMMA_PATH, mode="r", encoding="utf_8") as f:
    vaccination_lines = f.readlines()
    for vaccination1 in vaccination_lines:
        vaccination.append(vaccination1.rstrip().split(','))

In [31]:
import pandas as pd

df_count1 = pd.DataFrame(vaccination, columns=['day','prefecture','count'])
df_count1['count'] = df_count1['count'].astype(int)
df_count1

              day prefecture  count
0      2021-04-12          1    116
1      2021-04-12          1     89
2      2021-04-12          1     39
3      2021-04-12          1     26
4      2021-04-12          1     12
...           ...        ...    ...
41917  2021-07-22         47    134
41918  2021-07-22         47    107
41919  2021-07-22         47   1144
41920  2021-07-22         47      4
41921  2021-07-22         47      4

[41922 rows x 3 columns]

In [32]:
df_count2 = df_count1.groupby(['day','prefecture']).sum().reset_index()
df_count2

             day prefecture  count
0     2021-04-12          1    283
1     2021-04-12         10     86
2     2021-04-12         11    157
3     2021-04-12         12     18
4     2021-04-12         13    391
...          ...        ...    ...
4755  2021-07-22          5   4810
4756  2021-07-22          6   2272
4757  2021-07-22          7   2716
4758  2021-07-22          8  12630
4759  2021-07-22          9   3231

[4760 rows x 3 columns]

In [37]:
# 出力するデータを作成する
vaccination_rows = []
def apply_func(row1):
    vaccination_rows.append(" ".join([row1['day'], row1['prefecture'], str(row1['count'])]))
df_count2.apply(apply_func, axis=1)

# ファイル出力
with open(VACCINATION_WRITE_PATH, mode="w", encoding="utf_8") as f:
    f.write("\n".join(vaccination_rows))